//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4016
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// 原始文件名: Logging.cs
// 生成日期: 2009/8/17 12:24:29
namespace ESP.Logging
{
    
    /// <summary>
    /// 架构中不存在 LoggingEntities 的注释。
    /// </summary>
    public partial class LoggingEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“LoggingEntities”部分中的连接字符串初始化新 LoggingEntities 对象。
        /// </summary>
        public LoggingEntities() : 
                base("name=LoggingEntities", "LoggingEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 LoggingEntities 对象。
        /// </summary>
        public LoggingEntities(string connectionString) : 
                base(connectionString, "LoggingEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 LoggingEntities 对象。
        /// </summary>
        public LoggingEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "LoggingEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 LogEntries 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LogEntryInfo> LogEntries
        {
            get
            {
                if ((this._LogEntries == null))
                {
                    this._LogEntries = base.CreateQuery<LogEntryInfo>("[LogEntries]");
                }
                return this._LogEntries;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LogEntryInfo> _LogEntries;
        /// <summary>
        /// 架构中不存在 LogEntries 的注释。
        /// </summary>
        public void AddToLogEntries(LogEntryInfo logEntryInfo)
        {
            base.AddObject("LogEntries", logEntryInfo);
        }
    }
    /// <summary>
    /// 架构中不存在 ESP.Logging.LogEntryInfo 的注释。
    /// </summary>
    /// <KeyProperties>
    /// LogID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ESP.Logging", Name="LogEntryInfo")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LogEntryInfo : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 LogEntryInfo 对象。
        /// </summary>
        /// <param name="logID">LogID 的初始值。</param>
        /// <param name="logLevel">LogLevel 的初始值。</param>
        /// <param name="processID">ProcessID 的初始值。</param>
        /// <param name="threadID">ThreadID 的初始值。</param>
        /// <param name="userID">UserID 的初始值。</param>
        public static LogEntryInfo CreateLogEntryInfo(long logID, int logLevel, int processID, int threadID, int userID)
        {
            LogEntryInfo logEntryInfo = new LogEntryInfo();
            logEntryInfo.LogID = logID;
            logEntryInfo.LogLevel = logLevel;
            logEntryInfo.ProcessID = processID;
            logEntryInfo.ThreadID = threadID;
            logEntryInfo.UserID = userID;
            return logEntryInfo;
        }
        /// <summary>
        /// 架构中不存在属性 ApplicationName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName
        {
            get
            {
                return this._ApplicationName;
            }
            set
            {
                this.OnApplicationNameChanging(value);
                this.ReportPropertyChanging("ApplicationName");
                this._ApplicationName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ApplicationName");
                this.OnApplicationNameChanged();
            }
        }
        private string _ApplicationName;
        partial void OnApplicationNameChanging(string value);
        partial void OnApplicationNameChanged();
        /// <summary>
        /// 架构中不存在属性 ApplicationVersion 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationVersion
        {
            get
            {
                return this._ApplicationVersion;
            }
            set
            {
                this.OnApplicationVersionChanging(value);
                this.ReportPropertyChanging("ApplicationVersion");
                this._ApplicationVersion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ApplicationVersion");
                this.OnApplicationVersionChanged();
            }
        }
        private string _ApplicationVersion;
        partial void OnApplicationVersionChanging(string value);
        partial void OnApplicationVersionChanged();
        /// <summary>
        /// 架构中不存在属性 Category 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this.ReportPropertyChanging("Category");
                this._Category = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Category");
                this.OnCategoryChanged();
            }
        }
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// 架构中不存在属性 ClientAddress 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientAddress
        {
            get
            {
                return this._ClientAddress;
            }
            set
            {
                this.OnClientAddressChanging(value);
                this.ReportPropertyChanging("ClientAddress");
                this._ClientAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ClientAddress");
                this.OnClientAddressChanged();
            }
        }
        private string _ClientAddress;
        partial void OnClientAddressChanging(string value);
        partial void OnClientAddressChanged();
        /// <summary>
        /// 架构中不存在属性 ClientHostName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientHostName
        {
            get
            {
                return this._ClientHostName;
            }
            set
            {
                this.OnClientHostNameChanging(value);
                this.ReportPropertyChanging("ClientHostName");
                this._ClientHostName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ClientHostName");
                this.OnClientHostNameChanged();
            }
        }
        private string _ClientHostName;
        partial void OnClientHostNameChanging(string value);
        partial void OnClientHostNameChanged();
        /// <summary>
        /// 架构中不存在属性 ClientPort 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ClientPort
        {
            get
            {
                return this._ClientPort;
            }
            set
            {
                this.OnClientPortChanging(value);
                this.ReportPropertyChanging("ClientPort");
                this._ClientPort = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ClientPort");
                this.OnClientPortChanged();
            }
        }
        private global::System.Nullable<int> _ClientPort;
        partial void OnClientPortChanging(global::System.Nullable<int> value);
        partial void OnClientPortChanged();
        /// <summary>
        /// 架构中不存在属性 ExceptionInfo 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionInfo
        {
            get
            {
                return this._ExceptionInfo;
            }
            set
            {
                this.OnExceptionInfoChanging(value);
                this.ReportPropertyChanging("ExceptionInfo");
                this._ExceptionInfo = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ExceptionInfo");
                this.OnExceptionInfoChanged();
            }
        }
        private string _ExceptionInfo;
        partial void OnExceptionInfoChanging(string value);
        partial void OnExceptionInfoChanged();
        /// <summary>
        /// 架构中不存在属性 ExceptionType 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType
        {
            get
            {
                return this._ExceptionType;
            }
            set
            {
                this.OnExceptionTypeChanging(value);
                this.ReportPropertyChanging("ExceptionType");
                this._ExceptionType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ExceptionType");
                this.OnExceptionTypeChanged();
            }
        }
        private string _ExceptionType;
        partial void OnExceptionTypeChanging(string value);
        partial void OnExceptionTypeChanged();
        /// <summary>
        /// 架构中不存在属性 ExtendedProperties 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtendedProperties
        {
            get
            {
                return this._ExtendedProperties;
            }
            set
            {
                this.OnExtendedPropertiesChanging(value);
                this.ReportPropertyChanging("ExtendedProperties");
                this._ExtendedProperties = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ExtendedProperties");
                this.OnExtendedPropertiesChanged();
            }
        }
        private string _ExtendedProperties;
        partial void OnExtendedPropertiesChanging(string value);
        partial void OnExtendedPropertiesChanged();
        /// <summary>
        /// 架构中不存在属性 LogID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long LogID
        {
            get
            {
                return this._LogID;
            }
            set
            {
                this.OnLogIDChanging(value);
                this.ReportPropertyChanging("LogID");
                this._LogID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LogID");
                this.OnLogIDChanged();
            }
        }
        private long _LogID;
        partial void OnLogIDChanging(long value);
        partial void OnLogIDChanged();
        /// <summary>
        /// 架构中不存在属性 LogLevel 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LogLevel
        {
            get
            {
                return this._LogLevel;
            }
            set
            {
                this.OnLogLevelChanging(value);
                this.ReportPropertyChanging("LogLevel");
                this._LogLevel = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LogLevel");
                this.OnLogLevelChanged();
            }
        }
        private int _LogLevel;
        partial void OnLogLevelChanging(int value);
        partial void OnLogLevelChanged();
        /// <summary>
        /// 架构中不存在属性 LogTime 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> LogTime
        {
            get
            {
                return this._LogTime;
            }
            set
            {
                this.OnLogTimeChanging(value);
                this.ReportPropertyChanging("LogTime");
                this._LogTime = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LogTime");
                this.OnLogTimeChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _LogTime;
        partial void OnLogTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLogTimeChanged();
        /// <summary>
        /// 架构中不存在属性 Message 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this.ReportPropertyChanging("Message");
                this._Message = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Message");
                this.OnMessageChanged();
            }
        }
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// 架构中不存在属性 PagePath 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PagePath
        {
            get
            {
                return this._PagePath;
            }
            set
            {
                this.OnPagePathChanging(value);
                this.ReportPropertyChanging("PagePath");
                this._PagePath = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PagePath");
                this.OnPagePathChanged();
            }
        }
        private string _PagePath;
        partial void OnPagePathChanging(string value);
        partial void OnPagePathChanged();
        /// <summary>
        /// 架构中不存在属性 ProcessID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcessID
        {
            get
            {
                return this._ProcessID;
            }
            set
            {
                this.OnProcessIDChanging(value);
                this.ReportPropertyChanging("ProcessID");
                this._ProcessID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ProcessID");
                this.OnProcessIDChanged();
            }
        }
        private int _ProcessID;
        partial void OnProcessIDChanging(int value);
        partial void OnProcessIDChanged();
        /// <summary>
        /// 架构中不存在属性 RequestMethod 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestMethod
        {
            get
            {
                return this._RequestMethod;
            }
            set
            {
                this.OnRequestMethodChanging(value);
                this.ReportPropertyChanging("RequestMethod");
                this._RequestMethod = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RequestMethod");
                this.OnRequestMethodChanged();
            }
        }
        private string _RequestMethod;
        partial void OnRequestMethodChanging(string value);
        partial void OnRequestMethodChanged();
        /// <summary>
        /// 架构中不存在属性 ServerAddress 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerAddress
        {
            get
            {
                return this._ServerAddress;
            }
            set
            {
                this.OnServerAddressChanging(value);
                this.ReportPropertyChanging("ServerAddress");
                this._ServerAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ServerAddress");
                this.OnServerAddressChanged();
            }
        }
        private string _ServerAddress;
        partial void OnServerAddressChanging(string value);
        partial void OnServerAddressChanged();
        /// <summary>
        /// 架构中不存在属性 ServerHostName 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerHostName
        {
            get
            {
                return this._ServerHostName;
            }
            set
            {
                this.OnServerHostNameChanging(value);
                this.ReportPropertyChanging("ServerHostName");
                this._ServerHostName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ServerHostName");
                this.OnServerHostNameChanged();
            }
        }
        private string _ServerHostName;
        partial void OnServerHostNameChanging(string value);
        partial void OnServerHostNameChanged();
        /// <summary>
        /// 架构中不存在属性 ServerPort 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> ServerPort
        {
            get
            {
                return this._ServerPort;
            }
            set
            {
                this.OnServerPortChanging(value);
                this.ReportPropertyChanging("ServerPort");
                this._ServerPort = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ServerPort");
                this.OnServerPortChanged();
            }
        }
        private global::System.Nullable<int> _ServerPort;
        partial void OnServerPortChanging(global::System.Nullable<int> value);
        partial void OnServerPortChanged();
        /// <summary>
        /// 架构中不存在属性 ThreadID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ThreadID
        {
            get
            {
                return this._ThreadID;
            }
            set
            {
                this.OnThreadIDChanging(value);
                this.ReportPropertyChanging("ThreadID");
                this._ThreadID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ThreadID");
                this.OnThreadIDChanged();
            }
        }
        private int _ThreadID;
        partial void OnThreadIDChanging(int value);
        partial void OnThreadIDChanged();
        /// <summary>
        /// 架构中不存在属性 Url 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this.ReportPropertyChanging("Url");
                this._Url = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Url");
                this.OnUrlChanged();
            }
        }
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// 架构中不存在属性 UserAgent 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAgent
        {
            get
            {
                return this._UserAgent;
            }
            set
            {
                this.OnUserAgentChanging(value);
                this.ReportPropertyChanging("UserAgent");
                this._UserAgent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UserAgent");
                this.OnUserAgentChanged();
            }
        }
        private string _UserAgent;
        partial void OnUserAgentChanging(string value);
        partial void OnUserAgentChanged();
        /// <summary>
        /// 架构中不存在属性 UserID 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this.OnUserIDChanging(value);
                this.ReportPropertyChanging("UserID");
                this._UserID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserID");
                this.OnUserIDChanged();
            }
        }
        private int _UserID;
        partial void OnUserIDChanging(int value);
        partial void OnUserIDChanged();
    }
}
